"""
Django settings for buscam_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# ============================================================
# backend/buscam_project/settings.py
#
# RÔLE : Cerveau de configuration de tout le projet Django.
#        Django lit ce fichier AU DÉMARRAGE du serveur.
#        Chaque variable ici contrôle un comportement global.
#
# INTERACTIONS :
#    Lu par : manage.py, wsgi.py, asgi.py au lancement
#    Utilisé par : toutes les apps, tous les middlewares
# ============================================================
 
from pathlib import Path
from decouple import config, Csv

# ------------------------------------------------------------
# SECTION 1 : CHEMINS DE BASE
# ------------------------------------------------------------

# Path(__file__) = chemin absolu vers settings.py
# .resolve() = résout les liens symboliques
# .parent.parent = remonte 2 niveaux  dossier backend/
#
# Résultat : BASE_DIR = /chemin/vers/buscam/backend/
#
# UTILITÉ : toutes les autres config de chemins
# se basent sur BASE_DIR, jamais de chemins absolus codés en dur.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# ------------------------------------------------------------
# SECTION 2 : SÉCURITÉ
# ------------------------------------------------------------

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


# Clé utilisée par Django pour signer les cookies,
# les sessions, les tokens CSRF, etc.
# JAMAIS exposée en production. Lue depuis .env.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#!&8y!$n!nxq#^$g!04fc5*my^&o#&)#+$7ls@p4@k5ps3&ga-'


# En mode DEBUG=True :
#   - Les erreurs affichent la stack trace complète
#   - Django sert les fichiers statiques
#   - Plus de messages de logs
# En production : TOUJOURS False (fuite d'informations !)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Liste des domaines/IPs autorisés à accéder à cette API.
# config(..., cast=Csv()) transforme "localhost,127.0.0.1"
# en liste Python : ['localhost', '127.0.0.1']

ALLOWED_HOSTS = []


# ------------------------------------------------------------
# SECTION 3 : APPLICATIONS INSTALLÉES
# ------------------------------------------------------------
#
# Django NE CONNAÎT PAS vos apps automatiquement.
# Vous DEVEZ les déclarer ici.
#
# Ordre important :
#   1. Apps Django internes (django.contrib.*)
#   2. Apps tiers (rest_framework, corsheaders...)
#   3. VOS apps (utilisateurs, voyages, reservations)
#

# Application definition

INSTALLED_APPS = [
    # Apps Django natives — le noyau du framework
    'django.contrib.admin',          # Interface d'administration /admin
    'django.contrib.auth',           # Système d'authentification
    'django.contrib.contenttypes',   # Framework de types de contenu
    'django.contrib.sessions',       # Gestion des sessions
    'django.contrib.messages',       # Système de messages flash
    'django.contrib.staticfiles',    # Gestion des fichiers statiques
    
    # Apps tiers installées via pip
    'rest_framework', 
    'rest_framework.authtoken', # Django REST Framework  notre API
    'rest_framework_simplejwt',    # Authentification JWT
    'corsheaders',                 # Gestion du CORS (React  Django)
    'django_filters',                 # Pour filtrer mes recherches

    # NOS applications métier
    'utilisateurs',                # Gestion des voyageurs et agents
    'voyages',                     # Agences, bus, trajets
    'reservations',                # Billets, paiements

]


# ------------------------------------------------------------
# SECTION 4 : LES MIDDLEWARES
# ------------------------------------------------------------
#
# Un middleware = un "filtre" que CHAQUE requête HTTP traverse
# dans l'ordre, AVANT d'atteindre la vue.
# Et la réponse les traverse dans l'ordre INVERSE au retour.
#
# Flux : Requête  [M1  M2  M3  M4...]  Vue
#        Réponse  [M1  M2  M3  M4...]  Vue
#
#  CorsMiddleware DOIT être en PREMIER (avant tout autre).
# Sans ça, les requêtes OPTIONS (preflight) de React seront
# bloquées avant d'atteindre le middleware CORS.
#
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---- CORS : autorise React a parler à Django sur un autre port (5173 vs 8000)
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:5173',
#     'http://127.0.0.1:5173',
#     'http://localhost:3000',  # Au cas où vous testez sur le port 3000
# ]




# ------------------------------------------------------------
# SECTION 5 : ROUTAGE PRINCIPAL
# ------------------------------------------------------------

# Indique à Django quel fichier urls.py est le point d'entrée
# de toutes les URLs du projet.

ROOT_URLCONF = 'buscam_project.urls'


# ------------------------------------------------------------
# SECTION 6 : TEMPLATES (pages HTML classiques)
# ------------------------------------------------------------
#
# Notre API est "headless" (pas de HTML Django).
# On garde cette config pour l'interface /admin uniquement.
#

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'buscam_project.wsgi.application'



# ------------------------------------------------------------
# SECTION 7 : BASE DE DONNÉES
# ------------------------------------------------------------
#
# On utilise PostgreSQL (professionnel, robuste).
# Toutes les valeurs sensibles viennent du fichier .env.
#
# L'ORM Django traduit vos modèles Python en tables SQL.
# Vous n'écrivez JAMAIS de SQL brut (sauf cas exceptionnels).
#

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'options': '-c client_encoding=utf8'
        }
    }
}



# ------------------------------------------------------------
# SECTION 8 : VALIDATION DES MOTS DE PASSE
# ------------------------------------------------------------

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {    # Vérifie que le MDP n'est pas trop similaire aux infos utilisateur
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {    # Longueur minimum 8 caractères
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {    # Pas un mot de passe trop commun (liste noire)
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {    # Pas entièrement numérique
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# ------------------------------------------------------------
# SECTION 9 : INTERNATIONALISATION
# ------------------------------------------------------------

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'       # Interface admin en français

TIME_ZONE = 'Africa/Douala'   # Fuseau horaire Cameroun (UTC+1)

USE_I18N = True               # Activer les traductions

USE_TZ = True                 # Stocker les dates en UTC en DB
                              # (conversion auto vers Africa/Douala)





# ------------------------------------------------------------
# SECTION 10 : FICHIERS STATIQUES ET MÉDIAS
# ------------------------------------------------------------

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Fichiers statiques : CSS, JS, images du site
STATIC_URL = 'static/'
# STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Pour la collecte en prod

# Fichiers médias : uploads utilisateurs (photos de profil, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Stockés dans backend/media/



# ------------------------------------------------------------
# SECTION 11 : CLÉ PRIMAIRE PAR DÉFAUT
# ------------------------------------------------------------

# Depuis Django 3.2 : les nouvelles apps utilisent BigAutoField
# (entier 64-bit) au lieu d'AutoField (32-bit).
# Évite de manquer d'IDs pour les grandes tables.

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ------------------------------------------------------------
# SECTION 12 : CONFIGURATION CORS
# ------------------------------------------------------------
#
# CORS = Cross-Origin Resource Sharing
# Définit quels domaines peuvent appeler notre API.
#
# CORS_ALLOWED_ORIGINS : liste blanche stricte (recommandé)
# CORS_ALLOW_ALL_ORIGINS = True : autorise TOUT (dev seulement!)
#
CORS_ALLOWED_ORIGINS = [
    config('FRONTEND_URL', default='http://localhost:5173'),
    'http://127.0.0.1:5173',
    'http://localhost:3000',  # Au cas où vous testez sur le port 3000
]

# Autoriser les cookies cross-origin (nécessaire pour certains flux auth)

CORS_ALLOW_CREDENTIALS = True  # Autorise les cookies cross-origin (pour l'admin)
CORS_ALLOW_ALL_ORIGINS = False  # Ne pas autoriser tous les domaines (sécurité !)

# En-têtes HTTP autorisés dans les requêtes entrantes
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',      #  Pour les tokens JWT
    'content-type',       #  Pour envoyer du JSON
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT'
]



# ------------------------------------------------------------
# SECTION 13 : CONFIGURATION DJANGO REST FRAMEWORK
# ------------------------------------------------------------
#
# DRF a son propre dictionnaire de configuration.
# On définit ici les comportements GLOBAUX de l'API.
#
REST_FRAMEWORK = {

    # Comment DRF identifie l'utilisateur qui fait la requête ?
    # JWTAuthentication : lit le token Bearer dans le header Authorization
    # SessionAuthentication : lit le cookie de session (pour /admin)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    # Qui peut accéder aux endpoints par défaut ?
    # IsAuthenticated : il faut être connecté (token JWT valide)
    # On peut override au niveau de chaque View si besoin.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # Format de réponse par défaut : JSON
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],

    # Pagination globale : max 20 résultats par page
    # Évite de renvoyer 10 000 voyages d'un coup !
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}



# ------------------------------------------------------------
# SECTION 14 : CONFIGURATION JWT (SimpleJWT)
# ------------------------------------------------------------
#
# JWT = JSON Web Token
# Structure : Header.Payload.Signature (encodé en base64)
#
# Fonctionnement :
#   1. Utilisateur se connecte  Django renvoie 2 tokens :
#      - access_token  : valide 60 min, pour chaque requête
#      - refresh_token : valide 7 jours, pour renouveler l'access
#
#   2. React stocke ces tokens (localStorage ou mémoire)
#   3. Chaque requête inclut : Authorization: Bearer <access_token>
#   4. Django vérifie la signature  identifie l'utilisateur
#
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),   # Token d'accès : 1h
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Refresh : 7 jours
    'ROTATE_REFRESH_TOKENS': True,    # Nouveau refresh à chaque renouvellement
    'BLACKLIST_AFTER_ROTATION': True, # Ancien refresh invalidé (sécurité)
    'AUTH_HEADER_TYPES': ('Bearer',), # Format: "Authorization: Bearer <token>"
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}



# ------------------------------------------------------------
# SECTION 15 : MODÈLE UTILISATEUR PERSONNALISÉ
# ------------------------------------------------------------
#
# Indique à Django d'utiliser NOTRE modèle Utilisateur
# au lieu de django.contrib.auth.models.User
#
# ⚠️ CRITIQUE : doit être défini AVANT la première migration.
# Si vous migrez d'abord puis ajoutez ceci → ERREUR irréversible
# (il faudrait recréer toute la base de données)
#
AUTH_USER_MODEL = 'utilisateurs.Utilisateur'






# ============================================================
# AJOUTS POUR LA PRODUCTION (Render)
# ============================================================

import os
from decouple import config

# ── Sécurité production ───────────────────────────────────────
# En production : DEBUG=False dans le .env de Render
DEBUG = config('DEBUG', default=False, cast=bool)

# Render fournit automatiquement une variable DATABASE_URL
# On peut l'utiliser directement avec dj-database-url
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Production (Render) : utilise DATABASE_URL automatiquement
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Développement local : utilise les variables individuelles du .env
    DATABASES = {
        'default': {
            'ENGINE'  : 'django.db.backends.postgresql',
            'NAME'    : config('DB_NAME'),
            'USER'    : config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST'    : config('DB_HOST', default='localhost'),
            'PORT'    : config('DB_PORT', default='5432'),
        }
    }

# ── Fichiers statiques (nécessaire sur Render) ────────────────
STATIC_URL  = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise sert les fichiers statiques sans Nginx
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Ajouter whitenoise au middleware (après SecurityMiddleware)
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← AJOUTER ICI
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ── CORS Production ───────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    config('FRONTEND_URL', default='http://localhost:5173'),
]