# Generated by Django 6.0.6 on 2026-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, help_text='Format: 6XXXXXXXX (sans le +237)', max_length=15, null=True, unique=True),
        ),
    ]
