# Generated by Django 4.2.7 on 2026-06-14 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville_siege', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agences/logos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('gerant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agence_geree', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(help_text='Format: LT-1234-A', max_length=15, unique=True)),
                ('capacite', models.PositiveIntegerField(help_text='Nombre de places assises')),
                ('type_bus', models.CharField(choices=[('CLASSIQUE', 'Classique'), ('VIP', 'VIP'), ('BUSINESS', 'Business')], default='CLASSIQUE', max_length=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='voyages.agence')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(choices=[('YAOUNDE', 'Yaoundé'), ('DOUALA', 'Douala'), ('BAFOUSSAM', 'Bafoussam'), ('BAMENDA', 'Bamenda'), ('GAROUA', 'Garoua'), ('MAROUA', 'Maroua'), ('BERTOUA', 'Bertoua'), ('BUEA', 'Buea'), ('LIMBE', 'Limbé'), ('EBOLOWA', 'Ébolowa')], max_length=20)),
                ('ville_arrivee', models.CharField(choices=[('YAOUNDE', 'Yaoundé'), ('DOUALA', 'Douala'), ('BAFOUSSAM', 'Bafoussam'), ('BAMENDA', 'Bamenda'), ('GAROUA', 'Garoua'), ('MAROUA', 'Maroua'), ('BERTOUA', 'Bertoua'), ('BUEA', 'Buea'), ('LIMBE', 'Limbé'), ('EBOLOWA', 'Ébolowa')], max_length=20)),
                ('date_heure_depart', models.DateTimeField()),
                ('duree_estimee', models.DurationField(help_text='Durée estimée du trajet (ex: 4h00:00)')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PROGRAMME', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='voyages.agence')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='voyages.bus')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
                'ordering': ['date_heure_depart'],
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('numero_permis', models.CharField(max_length=30, unique=True)),
                ('bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_attitre', to='voyages.bus')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
            },
        ),
        migrations.AddConstraint(
            model_name='voyage',
            constraint=models.CheckConstraint(condition=models.Q(('ville_depart', models.F('ville_arrivee')), _negated=True), name='depart_different_arrivee'),
        ),
    ]
