# Generated by Django 4.2.7 on 2026-06-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siege', models.PositiveIntegerField(help_text='Numéro de siège dans le bus (1 à capacité_bus)')),
                ('numero_billet', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='voyages.voyage')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('statut_paiement', 'CONFIRME')), fields=('voyage', 'numero_siege'), name='siege_unique_par_voyage_si_confirme'),
        ),
    ]
